In [1]:
import pickle
import numpy as np

In [3]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embark = pickle.load(open('models/ohe_embark.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [9]:
user_input = np.array([2, 'male', 22, 'S'], dtype=object,).reshape(1,4)

In [10]:
user_input.shape

(1, 4)

In [14]:
import pandas as pd

In [16]:
sex = pd.DataFrame(user_input[:,1], columns=['sex'])

In [26]:
user_input_sex = ohe_sex.transform(sex)

In [18]:
user_input_sex

array([[0., 1.]])

In [24]:
embark = pd.DataFrame(user_input[:, 3], columns=['embark'])

In [25]:
user_input_embark = ohe_embark.transform(embark)

C:\Users\Ashrafkhan\anaconda3\envs\datascience\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(


In [23]:
user_input_embark

array([[0., 0., 1.]])

In [28]:
user_input_transformed = np.concatenate((user_input[:,[0,2]],user_input_sex,user_input_embark), axis=1)

In [30]:
user_input_transformed.shape

(1, 7)

In [31]:
clf.predict(user_input_transformed)

array([1], dtype=int64)